CREATE TABLE Accounts
(
	AccountID INT IDENTITY (1,1) PRIMARY KEY,
	CustomerID INT NOT NULL,
	AccountNumber NVARCHAR(20) NOT NULL UNIQUE,
	CreationDate DATETIME NOT NULL DEFAULT GETDATE(),
	CurrentBalance DECIMAL(18,2) NOT NULL DEFAULT 0,
);